# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Atac < Formula
  desc "Simple api client (postman like) in your terminal"
  homepage "https://github.com/Julien-cpsn/ATAC"
  url "https://github.com/Julien-cpsn/ATAC/archive/refs/tags/test_release.tar.gz"
  sha256 "6a16ef16bb4ad589060c959c6d6dcfb12b58a4667d942e36e4595818c3e9dbde"
  license "MIT"

  on_macos do
  end

  on_linux do
  end

  def install
    bin.install "atac"
  end
end
