# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Atac < Formula
  desc "Simple api client (postman like) in your terminal"
  homepage "https://github.com/Julien-cpsn/ATAC"
  url "https://github.com/Julien-cpsn/ATAC/archive/refs/tags/test_release.tar.gz"
  sha256 "ff9124557962d5727532cb06b80b319c1dbcbbd04fe5638067084a34229d7b0f"
  license "MIT"

  depends_on "bash" => :build

  on_macos do
  end

  on_linux do
  end

  def install
    bin.install "atac"
  end
end
